DROP TABLE IF EXISTS cyber_attacks;

CREATE TABLE cyber_attacks (
    record_id INTEGER,
    event_timestamp TIMESTAMP,
    source_ip VARCHAR(15),
    destination_ip VARCHAR(15),
    source_port INTEGER,
    destination_port INTEGER,
    protocol VARCHAR(10),
    packet_length INTEGER,
    packet_type VARCHAR(20),
    traffic_type VARCHAR(20),
    payload_data TEXT,
    malware_indicators VARCHAR(30),
    anomaly_score NUMERIC(6,2),
    alerts_warnings VARCHAR(20),
    attack_type VARCHAR(30),
    attack_signature VARCHAR(30),
    action_taken VARCHAR(20),
    severity_level VARCHAR(20),
    user_information VARCHAR(100),
    network_segment VARCHAR(30),
    geo_location VARCHAR(100),
    proxy_information VARCHAR(30),
    firewall_logs VARCHAR(30),
    ids_ips_alerts VARCHAR(30),
    log_source VARCHAR(30),
    browser VARCHAR(30),
    device_os VARCHAR(30),
    event_year INTEGER,
    event_month INTEGER,
    event_day INTEGER,
    event_hour INTEGER,
    event_minute INTEGER,
    event_second INTEGER,
    day_of_week INTEGER
);
